# Generated by Django 2.0.2 on 2018-05-23 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180523_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
