# Generated by Django 2.0.2 on 2018-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180523_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
